const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Cnds.CompareText
	];
};
self.C3_JsPropNameTable = [
	{btn_1: 0},
	{btn_2: 0},
	{btn_3: 0},
	{btn_4: 0},
	{btn_5: 0},
	{btn_6: 0},
	{btn_7: 0},
	{btn_8: 0},
	{btn_9: 0},
	{btn_0: 0},
	{btn_E: 0},
	{btn_I: 0},
	{btn_O: 0},
	{btn_P: 0},
	{btn_Q: 0},
	{btn_R: 0},
	{btn_T: 0},
	{btn_U: 0},
	{btn_W: 0},
	{btn_Y: 0},
	{btn_A: 0},
	{btn_D: 0},
	{btn_F: 0},
	{btn_G: 0},
	{btn_H: 0},
	{btn_J: 0},
	{btn_K: 0},
	{btn_L: 0},
	{btn_S: 0},
	{btn_Ñ: 0},
	{btn_B: 0},
	{btn_Borrar: 0},
	{btn_Buscar: 0},
	{btn_C: 0},
	{btn_M: 0},
	{btn_N: 0},
	{btn_V: 0},
	{btn_volver: 0},
	{btn_X: 0},
	{btn_Z: 0},
	{Button: 0},
	{Sprite: 0},
	{Texto: 0},
	{ControlTáctil: 0},
	{Sprite2: 0},
	{Texto2: 0},
	{Sprite3: 0},
	{btn_Imprimir: 0},
	{Texto3: 0}
];

self.InstanceType = {
	btn_1: class extends self.ISpriteInstance {},
	btn_2: class extends self.ISpriteInstance {},
	btn_3: class extends self.ISpriteInstance {},
	btn_4: class extends self.ISpriteInstance {},
	btn_5: class extends self.ISpriteInstance {},
	btn_6: class extends self.ISpriteInstance {},
	btn_7: class extends self.ISpriteInstance {},
	btn_8: class extends self.ISpriteInstance {},
	btn_9: class extends self.ISpriteInstance {},
	btn_0: class extends self.ISpriteInstance {},
	btn_E: class extends self.ISpriteInstance {},
	btn_I: class extends self.ISpriteInstance {},
	btn_O: class extends self.ISpriteInstance {},
	btn_P: class extends self.ISpriteInstance {},
	btn_Q: class extends self.ISpriteInstance {},
	btn_R: class extends self.ISpriteInstance {},
	btn_T: class extends self.ISpriteInstance {},
	btn_U: class extends self.ISpriteInstance {},
	btn_W: class extends self.ISpriteInstance {},
	btn_Y: class extends self.ISpriteInstance {},
	btn_A: class extends self.ISpriteInstance {},
	btn_D: class extends self.ISpriteInstance {},
	btn_F: class extends self.ISpriteInstance {},
	btn_G: class extends self.ISpriteInstance {},
	btn_H: class extends self.ISpriteInstance {},
	btn_J: class extends self.ISpriteInstance {},
	btn_K: class extends self.ISpriteInstance {},
	btn_L: class extends self.ISpriteInstance {},
	btn_S: class extends self.ISpriteInstance {},
	btn_Ñ: class extends self.ISpriteInstance {},
	btn_B: class extends self.ISpriteInstance {},
	btn_Borrar: class extends self.ISpriteInstance {},
	btn_Buscar: class extends self.ISpriteInstance {},
	btn_C: class extends self.ISpriteInstance {},
	btn_M: class extends self.ISpriteInstance {},
	btn_N: class extends self.ISpriteInstance {},
	btn_V: class extends self.ISpriteInstance {},
	btn_volver: class extends self.ISpriteInstance {},
	btn_X: class extends self.ISpriteInstance {},
	btn_Z: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	ControlTáctil: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	btn_Imprimir: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {}
}